const express=require("express")
const app=express()
const bodyParser=require("body-parser")
app.use(bodyParser.json())
app.use("/registrar",require("./registrar.js"))
app.use("/validar",require("./validar.js"))
app.use("/subirApuntes",require("./subirApuntes.js"))
app.use("/recibirApuntes",require("./recibirApuntes.js"))
app.use("/recibirApunte",require("./recibirApunte.js"))
app.use("/recibirProfesores",require("./recibirProfesores.js"))
app.use("/subirProfesor",require("./subirProfesor.js"))
app.listen(2005,()=>{
    console.log("ejecutando")
})
